const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  listPrinters: () => ipcRenderer.invoke('list-printers'),
  printHtml: (html, options) => ipcRenderer.invoke('print-html', { html, options }),
  saveBillPdf: (billNumber, htmlContent, customerName) => ipcRenderer.invoke('save-bill-pdf', { billNumber, htmlContent, customerName }),
  showFileInFolder: (billNumber, customerName) => ipcRenderer.invoke('show-file-in-folder', { billNumber, customerName }),
  openFile: (billNumber, customerName) => ipcRenderer.invoke('open-file', { billNumber, customerName }),
  copyFileToClipboard: (billNumber, customerName) => ipcRenderer.invoke('copy-file-to-clipboard', { billNumber, customerName }),
  saveCsv: (fileName, content, subfolder) => ipcRenderer.invoke('save-csv', { fileName, content, subfolder }),
  chooseBackupDirectory: () => ipcRenderer.invoke('choose-backup-dir'),
  saveJson: (fileName, content, directory) => ipcRenderer.invoke('save-json', { fileName, content, directory }),
  loadJson: (fileName, directory) => ipcRenderer.invoke('load-json', { fileName, directory }),
  getUserDataPath: () => ipcRenderer.invoke('get-user-data-path'),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onAppClose: (callback) => ipcRenderer.on('app-close', () => callback()),
  closeApp: () => ipcRenderer.send('close-app'),
  showAlert: (message, title) => ipcRenderer.sendSync('show-alert-sync', { message, title }),
  showConfirm: (message, title) => ipcRenderer.sendSync('show-confirm-sync', { message, title }),
  onWebhookOrder: (callback) => ipcRenderer.on('webhook-order', (event, data) => callback(data)),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (event, info) => callback(info)),
  onUpdateProgress: (callback) => ipcRenderer.on('update-progress', (event, progress) => callback(progress)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (event, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (event, err) => callback(err)),
  restartAndInstall: () => ipcRenderer.send('restart-and-install'),
  dbCall: (method, ...args) => ipcRenderer.invoke('db-call', { method, args }),
  getWhatsAppStatus: () => ipcRenderer.invoke('get-whatsapp-status'),
  initWhatsApp: () => ipcRenderer.invoke('init-whatsapp'),
  disconnectWhatsApp: () => ipcRenderer.invoke('disconnect-whatsapp'),
  sendWhatsAppAuto: (phone, text, billNumber, customerName) => ipcRenderer.invoke('send-whatsapp-auto', { phone, text, billNumber, customerName }),
  sendWhatsAppAds: (payload) => ipcRenderer.invoke('send-whatsapp-ads', payload),
  onWhatsAppStatus: (callback) => ipcRenderer.on('whatsapp-status', (event, data) => callback(data)),
  onWhatsAppQr: (callback) => ipcRenderer.on('whatsapp-qr', (event, data) => callback(data))
});

